apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      containers:
      - image: khalaf912/dolibarr:lastest
        name: dolibarr-app
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /var/www/html/dolibarr/htdocs/conf
          name: dolibarr-conf
        - mountPath: /var/www/html/dolibarr/htdocs/documents
          name: dolibarr-docs
      restartPolicy: Always
      volumes:
      - name: dolibarr-conf
        persistentVolumeClaim:
          claimName: dolibarr-conf
      - name: dolibarr-docs
        persistentVolumeClaim:
          claimName: dolibarr-docs
status: {}
